export const data = [
  {
    name: 'Test Case 1',
    data: ['Array', 1, 'getSize', 'getCapacity'],
    expectedResult: [null, 0, 1],
  },
  {
    name: 'Test Case 2',
    data: ['Array', 5, 'getSize', 'getCapacity'],
    expectedResult: [null, 0, 5],
  },
  {
    name: 'Test Case 3',
    data: [
      'Array',
      3,
      'pushback',
      1,
      'pushback',
      2,
      'pushback',
      3,
      'get',
      0,
      'get',
      1,
      'get',
      2,
    ],
    expectedResult: [null, null, null, null, 1, 2, 3],
  },
  {
    name: 'Test Case 4',
    data: [
      'Array',
      4,
      'pushback',
      1,
      'set',
      0,
      0,
      'pushback',
      2,
      'get',
      0,
      'get',
      1,
      'getCapacity',
      'popback',
    ],
    expectedResult: [null, null, null, null, 0, 2, 4, 2],
  },
  {
    name: 'Test Case 5',
    data: [
      'Array',
      5,
      'pushback',
      1,
      'pushback',
      2,
      'pushback',
      3,
      'popback',
      'popback',
      'get',
      0,
    ],
    expectedResult: [null, null, null, null, 3, 2, 1],
  },
  {
    name: 'Test Case 6',
    data: [
      'Array',
      2,
      'pushback',
      0,
      'pushback',
      1,
      'pushback',
      2,
      'getSize',
      'getCapacity',
    ],
    expectedResult: [null, null, null, null, 3, 4],
  },
  {
    name: 'Test Case 7',
    data: [
      'Array',
      3,
      'pushback',
      0,
      'pushback',
      1,
      'pushback',
      2,
      'getSize',
      'getCapacity',
    ],
    expectedResult: [null, null, null, null, 3, 3],
  },
  {
    name: 'Test Case 8',
    data: [
      'Array',
      5,
      'pushback',
      2,
      'pushback',
      4,
      'set',
      0,
      0,
      'get',
      0,
      'get',
      1,
      'getSize',
      'getCapacity',
    ],
    expectedResult: [null, null, null, null, 0, 4, 2, 5],
  },
  {
    name: 'Test Case 9',
    data: [
      'Array',
      1,
      'pushback',
      1,
      'getCapacity',
      'pushback',
      2,
      'getCapacity',
    ],
    expectedResult: [null, null, 1, null, 2],
  },
  {
    name: 'Test Case 10',
    data: [
      'Array',
      1,
      'getSize',
      'getCapacity',
      'pushback',
      1,
      'getSize',
      'getCapacity',
      'pushback',
      2,
      'getSize',
      'getCapacity',
      'get',
      1,
      'set',
      1,
      3,
      'get',
      1,
      'popback',
      'getSize',
      'getCapacity',
    ],
    expectedResult: [null, 0, 1, null, 1, 1, null, 2, 2, 2, null, 3, 3, 1, 2],
  },
  {
    name: 'Test Case 11',
    data: [
      'Array',
      1,
      'getSize',
      'getCapacity',
      'pushback',
      1,
      'pushback',
      2,
      'pushback',
      3,
      'pushback',
      4,
      'pushback',
      5,
      'pushback',
      6,
      'pushback',
      7,
      'pushback',
      8,
      'pushback',
      9,
      'getSize',
      'getCapacity',
      'popback',
      'popback',
      'popback',
      'popback',
      'popback',
      'popback',
      'popback',
      'popback',
      'popback',
      'getSize',
      'getCapacity',
    ],
    expectedResult: [
      null,
      0,
      1,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      9,
      16,
      9,
      8,
      7,
      6,
      5,
      4,
      3,
      2,
      1,
      0,
      16,
    ],
  },
];
